apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dashy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Matheus-Thurler/homelab-helm-apps.git
    targetRevision: HEAD
    # O ponto chave está aqui! Aponta para o diretório do chart específico.
    path: charts/dashy
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true